# playbook for install booker

- name: test
  host: booker_hosts
  gather_facts: false
  
  tasks:
  - name: Install git with depends
    apt:
      name: "git"
      state: present
      update_cache: yes

  - name: Remove old docker packages
    apt:
      name: "{{ item }}"
      state: absent
      update_cache: yes
    with_items:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    tags:
      - docker

  - name: Install docker depends
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    tags:
      - docker

      
  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
      
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
      
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
      
  - name: Update apt packages
    apt:
      update_cache: yes
    tags:
      - docker
      
  - name: Install docker
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with-items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    #notify: Start docker on boot
    tags:
      - docker

  - name: Make sure a service is running
    systemd:
      state: started
      name: docker

  - name: enable service httpd and ensure it is not masked
    systemd:
      name: docker
      enabled: yes
      masked: no

  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Creates booker directory
    file:
      path: /opt/booker
      state: directory
      recurse: yes

# ToDo: add ssh keys to repo
  - name: Clone booker repo
    git:
      repo: git@github.com:fincubator/booker.git
      dest: /opt/booker

  - name: Run docker containers
    shell: "cd /opt/booker/docker && docker-compose up -d"
    environment:
      DB_USER: "booker"
      DB_PASSWORD: "booker"
      DB_DATABASE: "booker"
      HTTP_PORT: "8080"
      HTTP_HOST: "0.0.0.0"
      ZMQ_PROTO: "tcp"
      ZMQ_PORT: "8081"
      ZMQ_HOST: "0.0.0.0"
      HTTP_PORT_HOST: "8080"